version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortcut
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortcut
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/url_shortcut
      - spring.datasource.username=postgres
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.postgresql.Driver
    ports:
      - "80:8080"
    depends_on:
      - db